//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetWeb.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assessment()
        {
            this.AssessmentQualifications = new HashSet<AssessmentQualification>();
            this.AssessmentTechnologies = new HashSet<AssessmentTechnology>();
        }
    
        public int AssessmentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime HireDate { get; set; }
        public string Email { get; set; }
        public int Gender { get; set; }
        public string Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentQualification> AssessmentQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentTechnology> AssessmentTechnologies { get; set; }
    }
}
