//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentQualification
    {
        public int AssessmentQualId { get; set; }
        public int AssessmentId { get; set; }
        public string Qualification { get; set; }
    
        public virtual Assessment Assessment { get; set; }
    }
}
